apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: chat-api-backend-policy
  namespace: default
spec:
  default:
    timeoutSec: 300
  targetRef:
    group: ""
    kind: Service
    name: clusterip-chat-api-svc
