steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-db-password'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret="db-pass-nvd11" --project="jason-hsbc" > /workspace/db_password.txt

- name: 'postgres:14'
  id: 'run-sql-script'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export PGPASSWORD=$$(cat /workspace/db_password.txt)
    psql -h 34.39.2.90 -U nvd11 -d default_db -f tbl_creation/init_schema.sql

serviceAccount: "projects/jason-hsbc/serviceAccounts/terraform@jason-hsbc.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
